name: Rami CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

permissions:
  contents: read

jobs:
  Run-Python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download Excel File
        run: |
          curl -o db.xlsx https://files.catbox.moe/r3rb3m.xlsx

      - name: Run Python Application
        run: |
          nohup python app.py db.xlsx &
          until curl -s -o /dev/null --fail http://localhost:5000; do
            echo "Waiting for Flask to start..."
            sleep 2
          done

      - name: Check Basic Routes (Home, Refresh)
        run: |
          curl -s -o /dev/null --fail http://localhost:5000
          curl -s -o /dev/null --fail http://localhost:5000/refresh

      - name: Check Search and Visitor Routes
        run: |
          curl -s -o /dev/null --fail --data "search_id=11111" http://localhost:5000/search
          curl -s -o /dev/null --fail http://localhost:5000/visitor/11111

      - name: Check Mark Entry/Exit Routes
        run: |
          curl -s -o /dev/null --fail http://localhost:5000/mark_entry/11111
          curl -s -o /dev/null --fail http://localhost:5000/mark_exit/11111


      
      - name: Check Logs File
        run: |
          curl -o time_log.csv --silent --fail http://localhost:5000/download_logs
          if [ ! -s time_log.csv ]; then echo "Log file is empty"; exit 1; fi
          echo "Downloaded file content:"
          cat time_log.csv
          
          if [[ "$(head -n 1 time_log.csv)" != "11111,Entry,"* ]]; then
            echo "Unexpected first line"; exit 1; fi

          if [[ "$(sed -n 2p time_log.csv)" != "11111,Exit,"* ]]; then
            echo "Unexpected second line"; exit 1; fi
  
  Build-Windows-Exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }

      - name: Build Windows Executable
        run: |
          pyinstaller buildrami.spec
          if (-not (Test-Path "dist")) { exit 1 }
          if (-not (Test-Path "dist\\rami\\rami.exe")) { exit 1 }

      - name: Download Excel File
        run: |
          Invoke-WebRequest -Uri "https://files.catbox.moe/r3rb3m.xlsx" -OutFile "db.xlsx"
      
      - name: Run Windows Executable
        run: |
          Start-Job -ScriptBlock {
              Start-Process -FilePath "dist\\rami\\rami.exe" -ArgumentList "db.xlsx" -NoNewWindow
          }
          Start-Sleep -Seconds 10
      - name: Check Web Request
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:5000" -UseBasicParsing -Method Head -ErrorAction SilentlyContinue
          if ($response.StatusCode -ne 200) { exit 1 }