name: Python Application CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download Excel File
        run: |
          curl -o db.xlsx https://files.catbox.moe/r3rb3m.xlsx

      - name: Run Python Application
        run: |
           nohup python app.py db.xlsx &
           sleep 5

      - name: Check Routes
        run: |
          set -e
          curl --silent --fail http://localhost:5000
          curl --silent --fail http://localhost:5000/refresh
          curl --silent --fail --data "search_id=11111" http://localhost:5000/search
          curl --silent --fail http://localhost:5000/visitor/11111
          curl --silent --fail http://localhost:5000/mark_entry/11111
          curl --silent --fail http://localhost:5000/mark_exit/11111

      
      - name: Check Logs File
        run: |
          curl -o time_log.csv --silent --fail http://localhost:5000/download_logs
          if [ ! -s time_log.csv ]; then echo "Log file is empty"; exit 1; fi
          echo "Downloaded file content:"
          cat time_log.csv
          
          if [[ "$(head -n 1 time_log.csv)" != "11111,Entry,"* ]]; then
            echo "Unexpected first line"; exit 1; fi

          if [[ "$(sed -n 2p time_log.csv)" != "11111,Exit,"* ]]; then
            echo "Unexpected second line"; exit 1; fi