name: Python Application CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download Excel File
        run: |
          curl -o my_file.xlsx https://files.catbox.moe/r3rb3m.xlsx

      - name: Run Python Application
        run: |
          python app.py my_file.xlsx

      - name: Check if website is running
        run: |
          curl --silent --fail http://localhost:5000 || exit 1
