name: Python Application CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

permissions:
  contents: read

jobs:
  check-python-execution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download Excel File
        run: |
          curl -o db.xlsx https://files.catbox.moe/r3rb3m.xlsx

      - name: Run Python Application
        run: |
          nohup python app.py db.xlsx &
          until curl -s -o /dev/null --fail http://localhost:5000; do
            echo "Waiting for Flask to start..."
            sleep 2
          done

      - name: Check Basic Routes (Home, Refresh)
        run: |
          curl -s -o /dev/null --fail http://localhost:5000
          curl -s -o /dev/null --fail http://localhost:5000/refresh

      - name: Check Search and Visitor Routes
        run: |
          curl -s -o /dev/null --fail --data "search_id=11111" http://localhost:5000/search
          curl -s -o /dev/null --fail http://localhost:5000/visitor/11111

      - name: Check Mark Entry/Exit Routes
        run: |
          curl -s -o /dev/null --fail http://localhost:5000/mark_entry/11111
          curl -s -o /dev/null --fail http://localhost:5000/mark_exit/11111


      
      - name: Check Logs File
        run: |
          curl -o time_log.csv --silent --fail http://localhost:5000/download_logs
          if [ ! -s time_log.csv ]; then echo "Log file is empty"; exit 1; fi
          echo "Downloaded file content:"
          cat time_log.csv
          
          if [[ "$(head -n 1 time_log.csv)" != "11111,Entry,"* ]]; then
            echo "Unexpected first line"; exit 1; fi

          if [[ "$(sed -n 2p time_log.csv)" != "11111,Exit,"* ]]; then
            echo "Unexpected second line"; exit 1; fi
  
  check-build-execution-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
        
      - name: Download Excel File
        run: |
          curl -o db.xlsx https://files.catbox.moe/r3rb3m.xlsx
      
      - name: Build Executable
        run: |
          pip install pyinstaller
          pyinstaller buildrami.spec
      
      - name: Run Executable
        run: |
          Start-Process -NoNewWindow -FilePath "dist\\rami.exe\\rami.exe" -ArgumentList "db.xlsx"
          Start-Sleep -Seconds 5
          while (-not (curl -s -o $null --fail http://localhost:5000)) {
            Write-Host "Waiting for Flask to start..."
            Start-Sleep -Seconds 2
          }

      - name: Check Basic Routes (Home, Refresh)
        run: |
          curl -s -o /dev/null --fail http://localhost:5000
          curl -s -o /dev/null --fail http://localhost:5000/refresh

      - name: Clean Up
        run: |
          rd /s /q dist